---
apiVersion: v1
kind: Service
metadata:
  name: restapi1
  labels:
    app: restapi1
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: restapi1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi1
  labels:
    app: restapi1
spec:
  selector:
    matchLabels:
      app: restapi1
  template:
    metadata:
      labels:
        app: restapi1
    spec:
      containers:
        - image: lkrzyzanek/helloworld-restapi:1.0
          name: restapi1
          ports:
            - containerPort: 8080
